namespace OpenGL;

public enum InternalFormat : ushort
{
    ColorIndex = GL_COLOR_INDEX,
    Red = GL_RED,
    Green = GL_GREEN,
    Blue = GL_BLUE,
    Alpha = GL_ALPHA,
    RGB = GL_RGB,
    RGBA = GL_RGBA,
    Luminance = GL_LUMINANCE,
    LuminanceAlpha = GL_LUMINANCE_ALPHA,
    Alpha4 = GL_ALPHA4,
    Alpha8 = GL_ALPHA8,
    Alpha12 = GL_ALPHA12,
    Alpha16 = GL_ALPHA16,
    Luninance4 = GL_LUMINANCE4,
    Luninance8 = GL_LUMINANCE8,
    Luninance12 = GL_LUMINANCE12,
    Luninance16 = GL_LUMINANCE16,
    Luninance4Alpha4 = GL_LUMINANCE4_ALPHA4,
    Luninance6Alpha2 = GL_LUMINANCE6_ALPHA2,
    Luninance8Alpha8 = GL_LUMINANCE8_ALPHA8,
    Luninance12Alpha4 = GL_LUMINANCE12_ALPHA4,
    Luninance12Alpha12 = GL_LUMINANCE12_ALPHA12,
    Luninance16Alpha16 = GL_LUMINANCE16_ALPHA16,
    Intensity = GL_INTENSITY,
    Intensity4 = GL_INTENSITY4,
    Intensity8 = GL_INTENSITY8,
    Intensity12 = GL_INTENSITY12,
    Intensity16 = GL_INTENSITY16,
    R3G3B2 = GL_R3_G3_B2,
    RGB4 = GL_RGB4,
    RGB5 = GL_RGB5,
    RGB8 = GL_RGB8,
    RGB10 = GL_RGB10,
    RGB12 = GL_RGB12,
    RGB16 = GL_RGB16,
    RGBA2 = GL_RGBA2,
    RGBA4 = GL_RGBA4,
    RGB5A1 = GL_RGB5_A1,
    RGBA8 = GL_RGBA8,
    RGB10A2 = GL_RGB10_A2,
    RGBA12 = GL_RGBA12,
    RGBA16 = GL_RGBA16,
}