namespace OpenGL;

public enum StateCap : ushort
{
    PointSmooth = GL_POINT_SMOOTH,
    AlphaTest = GL_ALPHA_TEST,
    Blend = GL_BLEND,
    ColorLogicOp = GL_COLOR_LOGIC_OP,
    ColorMaterialFace = GL_COLOR_MATERIAL_FACE,
    CullFace = GL_CULL_FACE,
    DepthTest = GL_DEPTH_TEST,
    Dither = GL_DITHER,
    Fog = GL_FOG,
    IndexLogicOp = GL_INDEX_LOGIC_OP,
    Lighting = GL_LIGHTING,
    LineSmooth = GL_LINE_SMOOTH,
    LineStipple = GL_LINE_STIPPLE,
    LogicOpMode = GL_LOGIC_OP_MODE,
    Normalize = GL_NORMALIZE,
    PointSmoothHint = GL_POINT_SMOOTH_HINT,
    PolygonOffsetFill = GL_POLYGON_OFFSET_FILL,
    PolygonOffsetLine = GL_POLYGON_OFFSET_LINE,
    PolygonOffsetPoint = GL_POLYGON_OFFSET_POINT,
    PolygonSmooth = GL_POLYGON_SMOOTH,
    PolygonStipple = GL_POLYGON_STIPPLE,
    ScissorTest = GL_SCISSOR_TEST,
    StencilTest = GL_STENCIL_TEST,
    Texture1D = GL_TEXTURE_1D,
    Texture2D = GL_TEXTURE_2D,
    TextureGenQ = GL_TEXTURE_GEN_Q,
    TextureGenS = GL_TEXTURE_GEN_S,
    TextureGenT = GL_TEXTURE_GEN_T,
    TextureGenR = GL_TEXTURE_GEN_R,
    ClipPlane0 = GL_CLIP_PLANE0,
    ClipPlane1 = GL_CLIP_PLANE1,
    ClipPlane2 = GL_CLIP_PLANE2,
    ClipPlane3 = GL_CLIP_PLANE3,
    ClipPlane4 = GL_CLIP_PLANE4,
    ClipPlane5 = GL_CLIP_PLANE5,
}